"""add posted_date to external_notices

Revision ID: 6e9b9b511749
Revises: d572e9d24f63
Create Date: 2026-01-20 10:42:22.481458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6e9b9b511749'
down_revision: Union[str, Sequence[str], None] = 'd572e9d24f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_notices', sa.Column('posted_date', sa.Date(), nullable=True))
    op.drop_column('external_notices', 'posted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_notices', sa.Column('posted_at', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('external_notices', 'posted_date')
    # ### end Alembic commands ###
