"""add external notices

Revision ID: 7f3b724345c1
Revises: c5ceb05eb8b0
Create Date: 2026-01-20 10:30:33.866781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f3b724345c1'
down_revision: Union[str, Sequence[str], None] = 'c5ceb05eb8b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('article_no', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('posted_at', sa.String(length=20), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('detail_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_no')
    )
    op.create_table('external_notice_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('attach_no', sa.String(length=50), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['notice_id'], ['external_notices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attach_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('external_notice_files')
    op.drop_table('external_notices')
    # ### end Alembic commands ###
