"""add inquiry academic_event_id

Revision ID: 840d7dd69236
Revises: ff08313f4384
Create Date: 2026-01-20 16:55:25.387192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '840d7dd69236'
down_revision: Union[str, Sequence[str], None] = 'ff08313f4384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('academic_events_ibfk_1'), 'academic_events', type_='foreignkey')
    op.drop_column('academic_events', 'academic_event_id')
    op.add_column('inquiries', sa.Column('academic_event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inquiries', 'academic_events', ['academic_event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inquiries', type_='foreignkey')
    op.drop_column('inquiries', 'academic_event_id')
    op.add_column('academic_events', sa.Column('academic_event_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('academic_events_ibfk_1'), 'academic_events', 'academic_events', ['academic_event_id'], ['id'])
    # ### end Alembic commands ###
