"""add inquiry academic_event_id

Revision ID: ff08313f4384
Revises: 39eb0ffbadd3
Create Date: 2026-01-20 16:54:31.152223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff08313f4384'
down_revision: Union[str, Sequence[str], None] = '39eb0ffbadd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_events', sa.Column('academic_event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'academic_events', 'academic_events', ['academic_event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'academic_events', type_='foreignkey')
    op.drop_column('academic_events', 'academic_event_id')
    # ### end Alembic commands ###
